---
name: Build and push Python Images to Google Cloud Platform
on:
  push:
    branches: [main]
jobs:
  build-push-artifact:
    name: Build and Push to GCP Artifact Registry
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: datatonic
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}
        export_default_credentials: true
    
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .
    
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
    
    - name: Push Docker Image to Artifact Registry
      run: |-
        docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/images/$IMAGE_NAME:latest
        docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/images/$IMAGE_NAME:latest
